urls.py
from django.conf.urls.defaults import *
from myobj import conf as MYCONF

urlpatterns = patterns(MYCONF.PROJECT_NAME + '.myobj.views',
    (r'^(?P<type>' + '|'.join(MYCONF.TYPES_DEF_CLASSES.keys()) + ')/(?P<params>.*)','options.get_url'),
    #site
    (r'^(?P<namem>[0-9a-z]*)/(?P<params>.*)','getsite.getpage'),
)

forms.py
from django import forms
from django.forms import ModelForm
from myobj.models import uClasses, objProperties
from myobj import conf as MYCONF

class actionsetparam(forms.Form):
    nameurl = forms.CharField(widget=forms.HiddenInput, max_length=255, required=False)
    idobj = forms.IntegerField(widget=forms.HiddenInput, required=False)
    idclass = forms.IntegerField(widget=forms.HiddenInput, required=False)
    params = forms.CharField(widget=forms.HiddenInput, required=False)
    objects = forms.CharField(widget=forms.HiddenInput, required=False)
    objectsno = forms.CharField(widget=forms.HiddenInput, required=False)
    exclude = forms.CharField(widget=forms.HiddenInput, max_length=1, required=False)
    order = forms.CharField(widget=forms.HiddenInput, required=False)
    order2 = forms.CharField(widget=forms.HiddenInput, required=False)
    searchcolumn = forms.CharField(widget=forms.HiddenInput, required=False)
    searchstrv = forms.CharField(widget=forms.HiddenInput, required=False)
    model = forms.CharField(widget=forms.HiddenInput, required=False)
    idobjparentobj = forms.CharField(widget=forms.HiddenInput, required=False)
    nameprop = forms.CharField(widget=forms.HiddenInput, required=False)

class FormCL(forms.Form):
    name = forms.CharField(max_length=30)
    codename = forms.SlugField(max_length=30)
    description = forms.CharField(max_length=255, widget=forms.Textarea, required=False)

class designUI(forms.Form):
    pass


class FormobjProperties(FormCL):
    myfield = forms.ChoiceField(MYCONF.TYPES_MYFIELDS_CHOICES)
    minfield = forms.CharField(max_length=4, required=False)
    maxfield = forms.CharField(max_length=4, required=False)
    required = forms.BooleanField(required=False)
    udefault = forms.CharField(max_length=255, required=False)


class FormUClasses(FormCL):
    tablespace = forms.ChoiceField(MYCONF.MYSPACE_TABLES_CHOICES)
    # if many-to-many then app '_m_NAMEmanytomanyfield'$
    properties_m_objProperties = forms.CharField(required=False, widget=forms.HiddenInput)

templates/myadmin/change_form.html
{% extends "myadmin/mybase.html" %}
{% block extrahead %}
{{ block.super }}
<link rel="stylesheet" type="text/css" href="/static/admin/css/forms.css" />
<script type="text/javascript" src="/admin/jsi18n/"></script>
<script type="text/javascript" src="/static/admin/js/core.js"></script>

<script type="text/javascript" src="/static/admin/js/admin/RelatedObjectLookups.js"></script>
<script type="text/javascript" src="/static/admin/js/jquery.min.js"></script>
<script type="text/javascript" src="/static/admin/js/jquery.init.js"></script>
<script type="text/javascript" src="/static/admin/js/actions.min.js"></script>
<script type="text/javascript" src="/static/admin/js/calendar.js"></script>
<script type="text/javascript" src="/static/admin/js/admin/DateTimeShortcuts.js"></script>

<script type="text/javascript" src="/static/myadmin/jhtmlarea/scripts/jHtmlArea-0.7.0.min.js"></script>
<link rel="Stylesheet" type="text/css" href="/static/myadmin/jhtmlarea/style/jHtmlArea.css" />

{% endblock %}

{% block content %}
<style>
.mycontent .myform {}
.vishidden {visibility: hidden}
</style>

{% autoescape off %}
<div class="mycontent">

<div class="headtop">{{header}}</div>
<div class="myform">



{% if myhtml.excepterr %}
<ul class="errorlist">
<li>{{myhtml.excepterr}}</li>
</ul>
{% endif %}



<form enctype="multipart/form-data" name="moref" method="post">{% csrf_token %}
<table>
{{myhtml.as_table}}
</table>

<input type="submit" name="onsubmit" value="send">
</form>
{% if myhtml.typesprops %}
<script>
var defhtninit = {
    toolbar: [
        ["html"],[ "bold", "italic", "underline", "strikethrough"],
        ["p", "h1", "h2", "h3", "h4", "h5", "h6"],
        ["link", "unlink", "|", "image", "|", "justifyLeft","justifyCenter","justifyRight", "|", "horizontalrule"]
    ]
}
var arriselemfiles = { {% for key, value in myhtml.typesprops.items %}{% if value = 'files' %}'{{ key }}': '{{value}}',{% endif %}{% endfor %} };
for(var namekey in arriselemfiles) {
    $('#id_'+namekey).parent().append(' <a href="' +'/' + mysystem.urlparam['myadm'] + '/' + mysystem.urlparam['class'] + '/' + mysystem.urlparam['paramslist'][0] + '/' + mysystem.urlparam['paramslist'][1] +'/obj/'+ mysystem.urlparam['paramslist'][3] +'/linksmodel/myobj.models__systemuploadsfiles/'+ namekey + '">ids model ' + arriselemfiles[namekey] + '</a>');
}

{% for key, value in myhtml.typesprops.items %}
{% if value == "html" %}
    $(function() {$('#id_{{ key }}').htmlarea(defhtninit)});
    $('#id_{{ key }}').attr('cols','100');$('#id_{{ key }}').attr('rows','20');
{% endif %}

{% if value == "date" %}
    $('#id_{{ key }}').attr('class','vDateField');
{% endif %}

{% if value == "time" %}
    $('#id_{{ key }}').attr('class','vTimeField');
{% endif %}

{% endfor %}
</script>
{% endif %}
</div>  

<script>



formobj = new Object();
formobj.arrmaxminfield = [{{ myfields.minmax|join:"," }}]
if($('#id_myfield').is('select')) {
	if(jQuery.inArray(parseInt($('#id_myfield').attr('value')), formobj.arrmaxminfield)=='-1') {
		$('#id_maxfield, #id_minfield').parent().parent().hide();
	}
	$('#id_myfield').change(function() {
		if(jQuery.inArray(parseInt(this.value), formobj.arrmaxminfield)!='-1') {
			$('#id_maxfield, #id_minfield').parent().parent().show();
		}
		else $('#id_maxfield, #id_minfield').parent().parent().hide();
	});
}
var dictparammodel = {
{% for key, value in myhtml.mtomfk.items %}
    '{{key}}': '{{value}}',
{% endfor %}
}
$(document.forms['moref']).find('input[name$="__prev_"]').each(function() {
    nameelem = $(this).attr('name').substr(0,$(this).attr('name').indexOf('__prev_'));
    sep = (mysystem.urlparam['paramslist'][0] == 'class')?'__':'___';
    arrelemmenlink = dictparammodel[nameelem].split(sep);
    $('#id_'+nameelem).parent().append(' <a href="'+'/' + mysystem.urlparam['myadm'] + '/' + mysystem.urlparam['class'] + '/' + mysystem.urlparam['paramslist'][0] + '/' + mysystem.urlparam['paramslist'][1] +'/obj/'+ mysystem.urlparam['paramslist'][3] +'/linksmodel/'+arrelemmenlink[0]+'/'+arrelemmenlink[1]+'">links</a>');
});

</script>




</div>
{% endautoescape %}

{% endblock %}

templates/myadmin/mybase.html
{% extends "admin/base_site.html" %}

{% block extrahead %}
<script type="text/javascript" src="/static/admin/js/jquery.min.js"></script>
<script>
function mysystem() {
	arrparem = (document.location.href.split('/')).slice(2);
	
	this.urlparam = {'domain': arrparem[0], 'myadm': arrparem[1]+'/'+arrparem[2], 'class': arrparem[3], 'paramslist': arrparem.slice(4)}
}
mysystem = new mysystem();

</script>
{% endblock %}

{% block title %}
{{ namecont }}
{% endblock %}

{% block breadcrumbs %}
<style>
.float_non {float:none !important;}
#content {padding:0;margin:0}
.main_menu {}
.main_menu li {display:block; float:left; position:relative;background: #D4D0C8;border: 1px solid #FCE7B0;  padding: 2px 0}
.main_menu li a {padding: 4px}
.main_menu .over {background: #D96201 !important}
.main_menu ul {padding:0;margin:0}
.main_menu li p {padding:0;margin:0}
.main_menu li ul {display:block; position:absolute; top:0; z-index:2;}
.main_menu li ul li {float:none; white-space: nowrap; }
.main_menu .classaddlinkm {background:#FE6602 !important}
.main_menu .filtclassobj {background:#C60000 !important}
.main_menu .classlinkm {background:#7FA0B0 !important;}
.botthr {border:1px solid #417690; background: #FCE7B0}
.dispnone {display:none !important}
.mycontent table {width:100%;border-collapse:collapse}
.mycontent table td,table th {vertical-align:top}
.mycontent a img {border:0}
.mycontent ol,ul{list-style:none}
.mycontent a {text-decoration:none;color:#000}
.mycontent .headtop {padding:1px; text-align:center;padding-bottom:10px;background:#FCEAB9}
.clear-bothblock {clear:both !important;width:1px;height:1px}
.altlink {border-bottom:1px dotted #0000CC; cursor:pointer}
</style>

{% autoescape off %}
<div class="main_menu">
	{{ topmenu }}
</div>
{% endautoescape %}

<div class="float_non botthr">&nbsp;</div><div>&nbsp;</div>

<script>
function ui_menu(str_parent_elem,istop) {
$(str_parent_elem+' li p').each(function() {
	elem_ul = $(this).next('ul:first');
	
	if(istop && $(this).parent().parent().parent().is(str_parent_elem)) 
		elem_ul.css({'top': $(this).parent().innerHeight()+'px'});
	else
		elem_ul.css({'left': $(this).parent().innerWidth()+'px'});
	
	
	$(this).parent().hover(function(event) {
		$(this).children('ul:first').toggle();
		
	});
});
$(str_parent_elem+' li ul').css('display','none');
$(str_parent_elem+' li a').live('mouseout mouseover',
function(e) { 
	if(e.type == 'mouseover') {
		$(this).parent().addClass('over');
	}
	else if(e.type == 'mouseout') {
		$(this).parent().removeClass('over');
	}
    $(this).click(function() {
        if($(this).attr('href') == '') {
            return false;
        }
    });
}
);
}
ui_menu('.main_menu',true);
</script>


{% endblock %}

templates/myadmin/static.html
{% extends "myadmin/mybase.html" %}

{% block content %}



<div class="mycontent">

<div class="headtop">{{head}}</div>
{% autoescape off %}
{{ myhtml }}
{% endautoescape %}
</div>


{% endblock %}